### ISSUE TITLE
error multiple definition of `PAIR_LIST_FIRST' in cluster_lists_defs.h

### ISSUE THREAD

**Issue by abrozzi** [jorvis/ergatis#5]
Dear @jorvis,

to reproduce results published in 2019 by Adonis D'Mello et al.:

[https://pubmed.ncbi.nlm.nih.gov/31842745/](https://pubmed.ncbi.nlm.nih.gov/31842745/)

I need to install ergatis on my Ubuntu machine.

When  running

`make install`

I get this error:

```
gcc ./cluster.o ./cluster_lists.o ./cluster_inp.o ./err.o -lm -lnsl -o ./cluster
/usr/bin/ld: ./cluster_lists.o:/opt/ergatis-v2r18/src/cluster/./cluster_lists_defs.h:17: multiple definition of `PAIR_LIST_FIRST'; ./cluster.o:/opt/ergatis-v2r18/src/cluster/./cluster_lists_defs.h:17: first defined here
/usr/bin/ld: ./cluster_lists.o:/opt/ergatis-v2r18/src/cluster/./cluster_lists_defs.h:17: multiple definition of `PAIR_LIST_LAST'; ./cluster.o:/opt/ergatis-v2r18/src/cluster/./cluster_lists_defs.h:17: first defined here
collect2: error: ld returned 1 exit status
```
and it fails installation.

Can you help me solving this?
Thank you very much!

Alessandro

**Comment by jorvis** [comment]
Alessandro -

Is there a particular reason you're using such an old version?  There are much newer ones [here](https://github.com/jorvis/ergatis/releases) on GitHub.  I had to track down the old SourceForge releases to find the one you're testing with.

I run the current version through the build process on Ubuntu just now and didn't run into issues.

**Comment by abrozzi** [comment]
Hi Joshua!
Thank for reply!

I debugged the C code and find out that in cluster_list_defs.h a missing “extern” solved the compilation.

ergatis is up and running.

Why sourceforge? Simply because o followed the link reported in the paper.

I am now about to plug and run this pipeline in ergatis:

https://github.com/admelloGithub/ReVac-package

I am reverse engineering this package to infer how to do it.

if you have any link to extra documentation is more than welcome 🙏 

Thanks again for your reply!
Alessandro
